### ISSUE TITLE
Nominating committee missing from Bylaws Document

### ISSUE THREAD

**Issue by honu-girl** [ESIPFed/Governance#1]
The text for the nominating committee needs to be added:

Section 1 – Electing officers

III.1.1 There shall be a Nominating Committee composed of five (5) members who shall be selected by the President and approved by the Executive Committee at the second Executive Committee Meeting after the Annual Meeting.

III.1.1.1 The Nominating Committee shall have at least one representative from ESIP Partnership Categories 1 through 3 as defined in Article I of these Bylaws.

III.1.1.2 The Committee shall nominate one or more candidates for each elective office, to be announced to the General Assembly prior to the election, at which time additional nominations may be made.

III.1.1.3 Additional nominations must be by at least two other Representatives.

Section 2 - ESIP prize nominations

III.1.2.1 The Nominating Committee will prepare nominations for ESIP Prizes at the request of the President.

**Comment by keiserk** [comment]
Not sure what to do with the added "Section 2 - ESIP prize nominations" since there is already an existing section 2 to Bylaw III, namely the "Replacing Officers" section.  Should III.1.2.1 be pulled up into section 1 (as III.1.1.4) or should there be a section 3 to bylaw III (so would become III.3.1.1) ?

Thoughts?

**Comment by honu-girl** [comment]
Not sure, actually, what the final approval was - @erinmr do you have a copy of what was sent out for electronic vote? I also think some other wording may have been added or tweaked.

If numbering wasn't addressed, I would suggest keeping the prize nominations as a separate section, whether that be 2. or 3. If it's 2., then we'd need to move the Replacing Officers to section 3.
