### ISSUE TITLE
Standing Committee Review of their respective Part under 1.3, Section 6.

### ISSUE THREAD

**Issue by honu-girl** [ESIPFed/Governance#11]
It might be time to have standing committees review their stated roles under P&P 1.3, Section 6, and update them if necessary. 

I would suggest maybe establishing some sort of regular timeline for review of their roles in the future.

**Comment by aebudden** [comment]
Committee chairs contacted. Reached out to Megan wrt placing on new committee chair orientation.

**Comment by aebudden** [comment]
Feedback received from all standing committees, Megan replied with respect to inclusion on orientation.
