### ISSUE TITLE
P&P 1.3, Section 6, establishing standing committees

### ISSUE THREAD

**Issue by honu-girl** [ESIPFed/Governance#8]
6.1.1 first sentence refers to the wrong section to create a new standing committee. Statement currently reads:
"Standing Committees are created by amendment of the Policies and Procedures to include **a new Section in Bylaw V**. " (bold added for emphasis)
It should read:
"Standing Committees are created by amendment of the Policies and Procedures to include **a new Part under this Section of the Policy and Procedures**."  (bold added for emphasis)

**Comment by aebudden** [comment]
Governance approved in 9/19
