### ISSUE TITLE
P&P 1.3, Section 6, Part 1 review

### ISSUE THREAD

**Issue by honu-girl** [ESIPFed/Governance#9]
Currently, under 6.1.3 each standing committee is required to hold at least one physical (in person?) meeting, with notification of all Partners. We don't actually do this necessarily, so this should be reviewed and/or modified.

6.1.4 states that standing committees report their activity to the Assembly at least quarterly. Again, in practicality, this is not done (although monthly reports are made to the Program Committee at this time). This should be reviewed and/or modified.

**Comment by aebudden** [comment]
Part one addressed with previous edits.
Part two to be discussed.

**Comment by aebudden** [comment]
Suggested edit from September 2023 Governance Committee meeting:

Administrative committees report to the Board quarterly, technical committees report out at the scheduled Program Committee meetings

To be discussed at the next Board meeting given potential changes to the Program Committee structure

**Comment by aebudden** [comment]
Changes presented to and approved by Board April 2024. PR merged into mail P&P.
